-- ========================================
-- 数字孪生城市地下管线管理系统 - 数据库初始化脚本
-- ========================================

CREATE DATABASE IF NOT EXISTS pipeline_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE pipeline_db;

-- ========================================
-- 一、管线资产表
-- ========================================

DROP TABLE IF EXISTS pipeline;
CREATE TABLE pipeline (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    pipeline_code VARCHAR(64) NOT NULL COMMENT '管线编号',
    pipeline_name VARCHAR(128) NOT NULL COMMENT '管线名称',
    pipeline_type TINYINT COMMENT '管线类型：1-给水 2-排水 3-燃气 4-电力 5-通信 6-热力 7-工业',
    material TINYINT COMMENT '材质：1-铸铁 2-钢管 3-PE 4-PVC 5-混凝土 6-其他',
    diameter DECIMAL(10,2) COMMENT '管径(mm)',
    length DECIMAL(10,2) COMMENT '管长(m)',
    buried_depth DECIMAL(10,2) COMMENT '埋设深度(m)',
    start_node_code VARCHAR(64) COMMENT '起始节点编号',
    end_node_code VARCHAR(64) COMMENT '终止节点编号',
    start_lng DECIMAL(12,8) COMMENT '起点经度',
    start_lat DECIMAL(12,8) COMMENT '起点纬度',
    end_lng DECIMAL(12,8) COMMENT '终点经度',
    end_lat DECIMAL(12,8) COMMENT '终点纬度',
    geometry TEXT COMMENT '中心线坐标（WKT格式）',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    road_name VARCHAR(128) COMMENT '道路名称',
    build_year VARCHAR(16) COMMENT '建设年代',
    owner_unit VARCHAR(128) COMMENT '产权单位',
    maintenance_unit VARCHAR(128) COMMENT '运维单位',
    status TINYINT DEFAULT 1 COMMENT '运行状态：1-正常 2-维修中 3-停用 4-废弃',
    pressure_level TINYINT COMMENT '压力等级：1-低压 2-中压 3-次高压 4-高压',
    section_info TEXT COMMENT '断面占用信息',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除：0-未删除 1-已删除',
    INDEX idx_pipeline_code (pipeline_code),
    INDEX idx_pipeline_type (pipeline_type),
    INDEX idx_area_code (area_code),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管线表';

DROP TABLE IF EXISTS pipeline_valve;
CREATE TABLE pipeline_valve (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    valve_code VARCHAR(64) NOT NULL COMMENT '阀门编号',
    valve_name VARCHAR(128) NOT NULL COMMENT '阀门名称',
    valve_type TINYINT COMMENT '阀门类型：1-闸阀 2-蝶阀 3-球阀 4-截止阀 5-止回阀',
    diameter DECIMAL(10,2) COMMENT '口径(mm)',
    lng DECIMAL(12,8) COMMENT '经度',
    lat DECIMAL(12,8) COMMENT '纬度',
    pipeline_code VARCHAR(64) COMMENT '所属管线编号',
    pipeline_id BIGINT COMMENT '关联管线ID',
    control_direction TINYINT COMMENT '控制方向：1-正向 2-反向',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    location VARCHAR(256) COMMENT '安装位置',
    install_date VARCHAR(16) COMMENT '安装日期',
    owner_unit VARCHAR(128) COMMENT '产权单位',
    status TINYINT DEFAULT 1 COMMENT '运行状态：1-正常 2-关闭 3-故障 4-维修中',
    remote_controllable TINYINT DEFAULT 0 COMMENT '是否可远程控制：0-否 1-是',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_valve_code (valve_code),
    INDEX idx_pipeline_id (pipeline_id),
    INDEX idx_area_code (area_code),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='阀门表';

DROP TABLE IF EXISTS pipeline_manhole;
CREATE TABLE pipeline_manhole (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    manhole_code VARCHAR(64) NOT NULL COMMENT '井盖编号',
    manhole_name VARCHAR(128) NOT NULL COMMENT '井盖名称',
    manhole_type TINYINT COMMENT '井盖类型：1-雨水 2-污水 3-给水 4-电力 5-通信 6-燃气 7-热力 8-综合',
    shape TINYINT COMMENT '形状：1-圆形 2-方形 3-矩形',
    size VARCHAR(64) COMMENT '规格尺寸',
    material TINYINT COMMENT '材质：1-铸铁 2-复合 3-水泥 4-其他',
    lng DECIMAL(12,8) COMMENT '经度',
    lat DECIMAL(12,8) COMMENT '纬度',
    depth DECIMAL(10,2) COMMENT '井室深度(m)',
    pipeline_code VARCHAR(64) COMMENT '所属管线编号',
    pipeline_id BIGINT COMMENT '关联管线ID',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    road_name VARCHAR(128) COMMENT '所在道路',
    install_date VARCHAR(16) COMMENT '安装日期',
    owner_unit VARCHAR(128) COMMENT '产权单位',
    status TINYINT DEFAULT 1 COMMENT '状态：1-正常 2-破损 3-缺失 4-维修中',
    has_safety_net TINYINT DEFAULT 0 COMMENT '是否有防坠网：0-否 1-是',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_manhole_code (manhole_code),
    INDEX idx_pipeline_id (pipeline_id),
    INDEX idx_area_code (area_code),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='井盖表';

DROP TABLE IF EXISTS pipeline_node;
CREATE TABLE pipeline_node (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    node_code VARCHAR(64) NOT NULL COMMENT '节点编号',
    node_name VARCHAR(128) COMMENT '节点名称',
    node_type TINYINT COMMENT '节点类型：1-三通 2-四通 3-弯头 4-异径 5-端点 6-其他',
    lng DECIMAL(12,8) COMMENT '经度',
    lat DECIMAL(12,8) COMMENT '纬度',
    elevation DECIMAL(10,2) COMMENT '高程(m)',
    buried_depth DECIMAL(10,2) COMMENT '埋设深度(m)',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    connected_pipeline_ids TEXT COMMENT '连接的管线ID列表（逗号分隔）',
    status TINYINT DEFAULT 1 COMMENT '状态：1-正常 2-维修中 3-停用',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_node_code (node_code),
    INDEX idx_area_code (area_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管网节点表';

-- ========================================
-- 二、传感器与告警表
-- ========================================

DROP TABLE IF EXISTS pipeline_sensor;
CREATE TABLE pipeline_sensor (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    sensor_code VARCHAR(64) NOT NULL COMMENT '传感器编号',
    sensor_name VARCHAR(128) NOT NULL COMMENT '传感器名称',
    sensor_type TINYINT COMMENT '传感器类型：1-压力 2-液位 3-流量 4-温度 5-振动 6-气体浓度 7-水质',
    model VARCHAR(64) COMMENT '型号',
    manufacturer VARCHAR(128) COMMENT '厂商',
    lng DECIMAL(12,8) COMMENT '经度',
    lat DECIMAL(12,8) COMMENT '纬度',
    install_location VARCHAR(256) COMMENT '安装位置描述',
    pipeline_id BIGINT COMMENT '关联管线ID',
    pipeline_code VARCHAR(64) COMMENT '关联管线编号',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    range_min DECIMAL(12,4) COMMENT '量程下限',
    range_max DECIMAL(12,4) COMMENT '量程上限',
    unit VARCHAR(16) COMMENT '单位',
    alarm_upper DECIMAL(12,4) COMMENT '告警阈值上限',
    alarm_lower DECIMAL(12,4) COMMENT '告警阈值下限',
    collect_interval INT COMMENT '采集频率(秒)',
    install_date VARCHAR(16) COMMENT '安装日期',
    maintenance_unit VARCHAR(128) COMMENT '运维单位',
    status TINYINT DEFAULT 1 COMMENT '状态：1-在线 2-离线 3-故障 4-维护中',
    last_value DECIMAL(12,4) COMMENT '最新读数',
    last_read_time VARCHAR(20) COMMENT '最新读数时间',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_sensor_code (sensor_code),
    INDEX idx_sensor_type (sensor_type),
    INDEX idx_pipeline_id (pipeline_id),
    INDEX idx_area_code (area_code),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='传感器表';

DROP TABLE IF EXISTS pipeline_sensor_reading;
CREATE TABLE pipeline_sensor_reading (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    sensor_id BIGINT NOT NULL COMMENT '传感器ID',
    sensor_code VARCHAR(64) COMMENT '传感器编号',
    sensor_type TINYINT COMMENT '传感器类型',
    reading_value DECIMAL(12,4) NOT NULL COMMENT '读数',
    unit VARCHAR(16) COMMENT '单位',
    collect_time VARCHAR(20) COMMENT '采集时间',
    is_alarm TINYINT DEFAULT 0 COMMENT '是否告警：0-否 1-是',
    alarm_level TINYINT COMMENT '告警级别：1-低 2-中 3-高 4-紧急',
    pipeline_id BIGINT COMMENT '关联管线ID',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_sensor_id (sensor_id),
    INDEX idx_collect_time (collect_time),
    INDEX idx_is_alarm (is_alarm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='传感器读数表';

DROP TABLE IF EXISTS pipeline_alarm;
CREATE TABLE pipeline_alarm (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    alarm_code VARCHAR(64) NOT NULL COMMENT '告警编号',
    alarm_type TINYINT COMMENT '告警类型：1-压力超限 2-液位超限 3-流量异常 4-温度异常 5-振动异常 6-气体泄漏 7-水质异常 8-设备离线 9-其他',
    alarm_level TINYINT COMMENT '告警级别：1-低 2-中 3-高 4-紧急',
    title VARCHAR(256) COMMENT '告警标题',
    content TEXT COMMENT '告警内容描述',
    sensor_id BIGINT COMMENT '触发传感器ID',
    sensor_code VARCHAR(64) COMMENT '触发传感器编号',
    pipeline_id BIGINT COMMENT '关联管线ID',
    pipeline_code VARCHAR(64) COMMENT '关联管线编号',
    lng DECIMAL(12,8) COMMENT '告警位置经度',
    lat DECIMAL(12,8) COMMENT '告警位置纬度',
    location VARCHAR(256) COMMENT '告警位置描述',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    threshold_value DECIMAL(12,4) COMMENT '告警阈值',
    actual_value DECIMAL(12,4) COMMENT '实际值',
    unit VARCHAR(16) COMMENT '单位',
    alarm_time VARCHAR(20) COMMENT '告警触发时间',
    status TINYINT DEFAULT 1 COMMENT '告警状态：1-待处理 2-处理中 3-已处置 4-已忽略',
    handler VARCHAR(64) COMMENT '处理人',
    handle_time VARCHAR(20) COMMENT '处理时间',
    handle_result TEXT COMMENT '处理结果说明',
    hazard_id BIGINT COMMENT '关联隐患点ID',
    work_order_id BIGINT COMMENT '关联工单ID',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_alarm_code (alarm_code),
    INDEX idx_alarm_type (alarm_type),
    INDEX idx_alarm_level (alarm_level),
    INDEX idx_status (status),
    INDEX idx_alarm_time (alarm_time),
    INDEX idx_pipeline_id (pipeline_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='告警记录表';

DROP TABLE IF EXISTS pipeline_hazard;
CREATE TABLE pipeline_hazard (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    hazard_code VARCHAR(64) NOT NULL COMMENT '隐患编号',
    title VARCHAR(256) NOT NULL COMMENT '隐患标题',
    hazard_type TINYINT COMMENT '隐患类型：1-腐蚀 2-泄漏 3-变形 4-沉降 5-占压 6-第三方破坏 7-材质老化 8-其他',
    risk_level TINYINT COMMENT '风险等级：1-低 2-中 3-高 4-极高',
    risk_score INT COMMENT '风险评分(0-100)',
    description TEXT COMMENT '隐患描述',
    lng DECIMAL(12,8) COMMENT '经度',
    lat DECIMAL(12,8) COMMENT '纬度',
    location VARCHAR(256) COMMENT '位置描述',
    pipeline_id BIGINT COMMENT '关联管线ID',
    pipeline_code VARCHAR(64) COMMENT '关联管线编号',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    discover_time VARCHAR(20) COMMENT '发现时间',
    discoverer VARCHAR(64) COMMENT '发现人',
    discover_source TINYINT COMMENT '发现来源：1-巡检 2-告警 3-施工发现 4-群众举报 5-其他',
    affect_scope TEXT COMMENT '影响范围描述',
    urgency TINYINT COMMENT '紧急程度：1-一般 2-较重 3-严重 4-特别严重',
    suggestion TEXT COMMENT '建议处置措施',
    images TEXT COMMENT '图片附件（JSON数组）',
    status TINYINT DEFAULT 1 COMMENT '隐患状态：1-待处置 2-处置中 3-已处置 4-已消除 5-持续监控',
    work_order_id BIGINT COMMENT '关联工单ID',
    alarm_id BIGINT COMMENT '关联告警ID',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_hazard_code (hazard_code),
    INDEX idx_hazard_type (hazard_type),
    INDEX idx_risk_level (risk_level),
    INDEX idx_status (status),
    INDEX idx_pipeline_id (pipeline_id),
    INDEX idx_area_code (area_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='隐患点表';

-- ========================================
-- 三、施工审批表
-- ========================================

DROP TABLE IF EXISTS excavation_application;
CREATE TABLE excavation_application (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    application_code VARCHAR(64) NOT NULL COMMENT '申请编号',
    project_name VARCHAR(256) NOT NULL COMMENT '项目名称',
    applicant_unit VARCHAR(128) NOT NULL COMMENT '申请单位',
    applicant VARCHAR(64) NOT NULL COMMENT '申请人',
    contact_phone VARCHAR(32) NOT NULL COMMENT '联系电话',
    construction_unit VARCHAR(128) COMMENT '施工单位',
    construction_leader VARCHAR(64) COMMENT '施工负责人',
    excavation_type TINYINT COMMENT '开挖类型：1-道路开挖 2-绿化开挖 3-建筑施工 4-管线铺设 5-其他',
    area_description TEXT COMMENT '开挖区域描述',
    geometry TEXT COMMENT '开挖区域边界坐标（WKT格式多边形）',
    center_lng DECIMAL(12,8) COMMENT '中心点经度',
    center_lat DECIMAL(12,8) COMMENT '中心点纬度',
    area DECIMAL(12,2) COMMENT '开挖面积(㎡)',
    depth DECIMAL(10,2) COMMENT '开挖深度(m)',
    plan_start_date VARCHAR(16) COMMENT '计划开工日期',
    plan_end_date VARCHAR(16) COMMENT '计划完工日期',
    construction_content TEXT COMMENT '施工内容描述',
    protection_measures TEXT COMMENT '防护措施说明',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    involved_pipeline_count INT DEFAULT 0 COMMENT '涉及管线数量',
    has_conflict TINYINT DEFAULT 0 COMMENT '是否存在冲突：0-否 1-是',
    conflict_pipeline_types VARCHAR(64) COMMENT '冲突管线类型（逗号分隔）',
    affected_road_count INT DEFAULT 0 COMMENT '影响道路数量',
    affected_road_names TEXT COMMENT '影响道路名称（逗号分隔）',
    status TINYINT DEFAULT 1 COMMENT '申请状态：1-待提交 2-待校核 3-校核通过 4-校核不通过 5-待审批 6-审批通过 7-审批不通过 8-已开工 9-已完工 10-已归档',
    review_opinion TEXT COMMENT '校核意见',
    reviewer VARCHAR(64) COMMENT '校核人',
    review_time VARCHAR(20) COMMENT '校核时间',
    approval_opinion TEXT COMMENT '审批意见',
    approver VARCHAR(64) COMMENT '审批人',
    approval_time VARCHAR(20) COMMENT '审批时间',
    attachments TEXT COMMENT '附件（JSON数组）',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_application_code (application_code),
    INDEX idx_status (status),
    INDEX idx_area_code (area_code),
    INDEX idx_applicant_unit (applicant_unit)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='开挖申请表';

DROP TABLE IF EXISTS pipeline_conflict;
CREATE TABLE pipeline_conflict (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    conflict_code VARCHAR(64) NOT NULL COMMENT '冲突编号',
    application_id BIGINT COMMENT '关联开挖申请ID',
    application_code VARCHAR(64) COMMENT '关联开挖申请编号',
    pipeline_id BIGINT COMMENT '管线ID',
    pipeline_code VARCHAR(64) COMMENT '管线编号',
    pipeline_name VARCHAR(128) COMMENT '管线名称',
    pipeline_type TINYINT COMMENT '管线类型',
    conflict_type TINYINT COMMENT '冲突类型：1-水平净距不足 2-垂直净距不足 3-交叉冲突 4-开挖破坏风险 5-占压',
    conflict_level TINYINT COMMENT '冲突等级：1-一般 2-较重 3-严重 4-特别严重',
    lng DECIMAL(12,8) COMMENT '冲突位置经度',
    lat DECIMAL(12,8) COMMENT '冲突位置纬度',
    location VARCHAR(256) COMMENT '冲突位置描述',
    horizontal_distance DECIMAL(10,2) COMMENT '水平净距(m)',
    required_horizontal_distance DECIMAL(10,2) COMMENT '规范要求水平净距(m)',
    vertical_distance DECIMAL(10,2) COMMENT '垂直净距(m)',
    required_vertical_distance DECIMAL(10,2) COMMENT '规范要求垂直净距(m)',
    description TEXT COMMENT '冲突说明',
    suggestion TEXT COMMENT '处置建议',
    owner_unit VARCHAR(128) COMMENT '产权单位',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    status TINYINT DEFAULT 1 COMMENT '处理状态：1-待处理 2-已协调 3-已处置 4-已忽略',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_application_id (application_id),
    INDEX idx_pipeline_id (pipeline_id),
    INDEX idx_conflict_level (conflict_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管线冲突表';

DROP TABLE IF EXISTS emergency_valve_suggestion;
CREATE TABLE emergency_valve_suggestion (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    suggestion_code VARCHAR(64) NOT NULL COMMENT '建议编号',
    application_id BIGINT COMMENT '关联开挖申请ID',
    pipeline_id BIGINT COMMENT '关联管线ID',
    pipeline_code VARCHAR(64) COMMENT '关联管线编号',
    pipeline_name VARCHAR(128) COMMENT '关联管线名称',
    reason_type TINYINT COMMENT '关阀原因：1-施工防护 2-抢修作业 3-应急处置 4-其他',
    valve_ids TEXT COMMENT '建议关闭阀门ID列表（JSON数组）',
    valve_codes TEXT COMMENT '建议关闭阀门编号列表（逗号分隔）',
    valve_names TEXT COMMENT '建议关闭阀门名称列表（逗号分隔）',
    affected_pipeline_count INT COMMENT '受影响管线数量',
    affected_area TEXT COMMENT '受影响区域描述',
    estimated_affected_users INT COMMENT '预计影响用户数',
    estimated_duration INT COMMENT '预计影响时长(小时)',
    operation_steps TEXT COMMENT '关阀操作步骤说明',
    safety_notes TEXT COMMENT '安全注意事项',
    recovery_plan TEXT COMMENT '恢复供气/供水方案',
    status TINYINT DEFAULT 1 COMMENT '建议状态：1-建议 2-已确认 3-已执行 4-已取消',
    confirmer VARCHAR(64) COMMENT '确认人',
    confirm_time VARCHAR(20) COMMENT '确认时间',
    executor VARCHAR(64) COMMENT '执行人',
    execute_time VARCHAR(20) COMMENT '执行时间',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_application_id (application_id),
    INDEX idx_pipeline_id (pipeline_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应急关阀建议表';

-- ========================================
-- 四、巡检与维修表
-- ========================================

DROP TABLE IF EXISTS inspection_route;
CREATE TABLE inspection_route (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    route_code VARCHAR(64) NOT NULL COMMENT '路线编号',
    route_name VARCHAR(128) NOT NULL COMMENT '路线名称',
    route_type TINYINT COMMENT '路线类型：1-日常巡检 2-专项巡检 3-重点巡检 4-应急巡检',
    pipeline_type TINYINT COMMENT '管线类型：1-给水 2-排水 3-燃气 4-电力 5-通信 6-热力 7-全部',
    check_points MEDIUMTEXT COMMENT '巡检点列表（JSON数组）',
    start_lng DECIMAL(12,8) COMMENT '起点经度',
    start_lat DECIMAL(12,8) COMMENT '起点纬度',
    end_lng DECIMAL(12,8) COMMENT '终点经度',
    end_lat DECIMAL(12,8) COMMENT '终点纬度',
    total_length DECIMAL(10,2) COMMENT '路线总长度(km)',
    estimated_duration INT COMMENT '预计巡检时长(分钟)',
    pipeline_ids TEXT COMMENT '涉及管线ID列表（逗号分隔）',
    manhole_ids TEXT COMMENT '涉及井盖ID列表（逗号分隔）',
    valve_ids TEXT COMMENT '涉及阀门ID列表（逗号分隔）',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    responsible_dept VARCHAR(128) COMMENT '负责部门',
    responsible_person VARCHAR(64) COMMENT '负责人员',
    cycle_type TINYINT COMMENT '巡检周期：1-每日 2-每周 3-每半月 4-每月 5-每季度 6-每年',
    description TEXT COMMENT '路线说明',
    status TINYINT DEFAULT 1 COMMENT '状态：1-启用 2-停用',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_route_code (route_code),
    INDEX idx_route_type (route_type),
    INDEX idx_area_code (area_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检路线表';

DROP TABLE IF EXISTS inspection_record;
CREATE TABLE inspection_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    record_code VARCHAR(64) NOT NULL COMMENT '记录编号',
    route_id BIGINT COMMENT '关联路线ID',
    route_code VARCHAR(64) COMMENT '关联路线编号',
    route_name VARCHAR(128) COMMENT '关联路线名称',
    inspector_id BIGINT COMMENT '巡检人ID',
    inspector_name VARCHAR(64) COMMENT '巡检人姓名',
    start_time VARCHAR(20) COMMENT '巡检开始时间',
    end_time VARCHAR(20) COMMENT '巡检结束时间',
    duration INT COMMENT '巡检时长(分钟)',
    actual_distance DECIMAL(10,2) COMMENT '实际巡检里程(km)',
    trajectory MEDIUMTEXT COMMENT '巡检轨迹坐标（JSON数组）',
    total_points INT COMMENT '应巡检点数',
    checked_points INT COMMENT '已巡检点数',
    completion_rate INT COMMENT '巡检完成率(%)',
    defect_count INT DEFAULT 0 COMMENT '发现缺陷数量',
    reported_defect_count INT DEFAULT 0 COMMENT '已上报缺陷数量',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    description TEXT COMMENT '巡检情况说明',
    status TINYINT DEFAULT 1 COMMENT '巡检状态：1-进行中 2-已完成 3-异常中断 4-已取消',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_record_code (record_code),
    INDEX idx_route_id (route_id),
    INDEX idx_inspector_id (inspector_id),
    INDEX idx_status (status),
    INDEX idx_start_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检记录表';

DROP TABLE IF EXISTS defect_report;
CREATE TABLE defect_report (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    defect_code VARCHAR(64) NOT NULL COMMENT '缺陷编号',
    title VARCHAR(256) NOT NULL COMMENT '缺陷标题',
    defect_type TINYINT COMMENT '缺陷类型：1-管道腐蚀 2-管道泄漏 3-管道变形 4-井盖破损 5-井盖缺失 6-阀门故障 7-接口渗漏 8-沉降 9-占压 10-其他',
    defect_level TINYINT COMMENT '缺陷等级：1-一般 2-较重 3-严重 4-紧急',
    description TEXT COMMENT '缺陷描述',
    lng DECIMAL(12,8) COMMENT '经度',
    lat DECIMAL(12,8) COMMENT '纬度',
    location VARCHAR(256) COMMENT '位置描述',
    pipeline_id BIGINT COMMENT '关联管线ID',
    pipeline_code VARCHAR(64) COMMENT '关联管线编号',
    manhole_id BIGINT COMMENT '关联井盖ID',
    valve_id BIGINT COMMENT '关联阀门ID',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    inspection_record_id BIGINT COMMENT '关联巡检记录ID',
    reporter_id BIGINT COMMENT '上报人ID',
    reporter_name VARCHAR(64) COMMENT '上报人姓名',
    report_source TINYINT COMMENT '上报来源：1-巡检App 2-一张图平台 3-施工审批 4-群众举报 5-其他',
    report_time VARCHAR(20) COMMENT '上报时间',
    images TEXT COMMENT '图片附件（JSON数组）',
    voice_url VARCHAR(512) COMMENT '语音附件URL',
    video_url VARCHAR(512) COMMENT '视频附件URL',
    status TINYINT DEFAULT 1 COMMENT '缺陷状态：1-待受理 2-已受理 3-处理中 4-已修复 5-已验证 6-已归档 7-已驳回',
    receiver VARCHAR(64) COMMENT '受理人',
    receive_time VARCHAR(20) COMMENT '受理时间',
    work_order_id BIGINT COMMENT '关联工单ID',
    hazard_id BIGINT COMMENT '关联隐患点ID',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_defect_code (defect_code),
    INDEX idx_defect_type (defect_type),
    INDEX idx_defect_level (defect_level),
    INDEX idx_status (status),
    INDEX idx_pipeline_id (pipeline_id),
    INDEX idx_area_code (area_code),
    INDEX idx_report_time (report_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='缺陷上报表';

DROP TABLE IF EXISTS work_order;
CREATE TABLE work_order (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    order_code VARCHAR(64) NOT NULL COMMENT '工单编号',
    title VARCHAR(256) NOT NULL COMMENT '工单标题',
    order_type TINYINT COMMENT '工单类型：1-维修 2-抢修 3-巡检整改 4-改造 5-日常维护',
    order_source TINYINT COMMENT '工单来源：1-告警 2-隐患 3-缺陷 4-巡检 5-开挖施工 6-其他',
    urgency TINYINT COMMENT '紧急程度：1-一般 2-较重 3-严重 4-紧急',
    description TEXT COMMENT '工单描述',
    lng DECIMAL(12,8) COMMENT '经度',
    lat DECIMAL(12,8) COMMENT '纬度',
    location VARCHAR(256) COMMENT '位置描述',
    pipeline_id BIGINT COMMENT '关联管线ID',
    pipeline_code VARCHAR(64) COMMENT '关联管线编号',
    manhole_id BIGINT COMMENT '关联井盖ID',
    valve_id BIGINT COMMENT '关联阀门ID',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    area_name VARCHAR(128) COMMENT '所属区域名称',
    alarm_id BIGINT COMMENT '关联告警ID',
    hazard_id BIGINT COMMENT '关联隐患ID',
    defect_id BIGINT COMMENT '关联缺陷ID',
    application_id BIGINT COMMENT '关联开挖申请ID',
    creator VARCHAR(64) COMMENT '创建人',
    create_order_time VARCHAR(20) COMMENT '创建时间',
    dispatch_time VARCHAR(20) COMMENT '派单时间',
    dispatcher VARCHAR(64) COMMENT '派单人',
    undertake_dept VARCHAR(128) COMMENT '承办部门',
    undertaker VARCHAR(64) COMMENT '承办人',
    contact_phone VARCHAR(32) COMMENT '联系电话',
    expect_complete_time VARCHAR(20) COMMENT '预计完成时间',
    actual_start_time VARCHAR(20) COMMENT '实际开始时间',
    actual_complete_time VARCHAR(20) COMMENT '实际完成时间',
    used_hours DECIMAL(10,2) COMMENT '用时(小时)',
    materials TEXT COMMENT '材料消耗（JSON数组）',
    labor_cost VARCHAR(256) COMMENT '人工消耗',
    construction_workers VARCHAR(256) COMMENT '施工人员',
    disposal_plan TEXT COMMENT '处置方案说明',
    disposal_process TEXT COMMENT '处置过程描述',
    disposal_result TEXT COMMENT '处置结果说明',
    acceptor VARCHAR(64) COMMENT '验收人',
    accept_time VARCHAR(20) COMMENT '验收时间',
    accept_opinion TEXT COMMENT '验收意见',
    accept_qualified TINYINT COMMENT '验收是否合格：0-否 1-是',
    before_images TEXT COMMENT '施工前图片（JSON数组）',
    during_images TEXT COMMENT '施工中图片（JSON数组）',
    after_images TEXT COMMENT '施工后图片（JSON数组）',
    status TINYINT DEFAULT 1 COMMENT '工单状态：1-待派单 2-已派单 3-处理中 4-待验收 5-已完成 6-已取消 7-已驳回',
    current_node VARCHAR(64) COMMENT '当前处理节点',
    progress INT COMMENT '流程进度(%)',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_order_code (order_code),
    INDEX idx_order_type (order_type),
    INDEX idx_urgency (urgency),
    INDEX idx_status (status),
    INDEX idx_undertaker (undertaker),
    INDEX idx_pipeline_id (pipeline_id),
    INDEX idx_area_code (area_code),
    INDEX idx_create_order_time (create_order_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='维修工单表';

DROP TABLE IF EXISTS work_order_flow;
CREATE TABLE work_order_flow (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    work_order_id BIGINT NOT NULL COMMENT '工单ID',
    order_code VARCHAR(64) COMMENT '工单编号',
    node_name VARCHAR(64) COMMENT '流转节点名称',
    operation_type TINYINT COMMENT '操作类型：1-创建 2-派单 3-接单 4-开始处理 5-上报进度 6-申请验收 7-验收 8-驳回 9-完成 10-取消',
    before_status TINYINT COMMENT '操作前状态',
    after_status TINYINT COMMENT '操作后状态',
    operator VARCHAR(64) COMMENT '操作人',
    operator_dept VARCHAR(128) COMMENT '操作人所属部门',
    operate_time VARCHAR(20) COMMENT '操作时间',
    opinion TEXT COMMENT '操作意见',
    attachments TEXT COMMENT '附件（JSON数组）',
    next_handler VARCHAR(64) COMMENT '下一节点处理人',
    next_handler_dept VARCHAR(128) COMMENT '下一节点处理部门',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_work_order_id (work_order_id),
    INDEX idx_operate_time (operate_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工单流转记录表';

-- ========================================
-- 五、历史追溯与权限表
-- ========================================

DROP TABLE IF EXISTS change_history;
CREATE TABLE change_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    business_type TINYINT COMMENT '关联业务类型：1-管线 2-阀门 3-井盖 4-传感器 5-隐患 6-工单 7-开挖申请 8-巡检记录',
    business_id BIGINT COMMENT '关联业务ID',
    business_code VARCHAR(64) COMMENT '关联业务编号',
    change_type TINYINT COMMENT '变更类型：1-新增 2-修改 3-删除 4-状态变更 5-流程流转',
    field_name VARCHAR(64) COMMENT '变更字段名',
    old_value TEXT COMMENT '变更前值',
    new_value TEXT COMMENT '变更后值',
    description TEXT COMMENT '变更说明',
    operator VARCHAR(64) COMMENT '操作人',
    operator_dept VARCHAR(128) COMMENT '操作人所属部门',
    operate_time VARCHAR(20) COMMENT '操作时间',
    operate_ip VARCHAR(64) COMMENT '操作IP',
    area_code VARCHAR(32) COMMENT '所属区域编码',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_business (business_type, business_id),
    INDEX idx_operator (operator),
    INDEX idx_operate_time (operate_time),
    INDEX idx_area_code (area_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='变更历史记录表';

DROP TABLE IF EXISTS sharing_scope;
CREATE TABLE sharing_scope (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    resource_type TINYINT COMMENT '资源类型：1-管线 2-阀门 3-井盖 4-传感器 5-隐患 6-工单 7-开挖申请 8-全部',
    resource_id BIGINT DEFAULT 0 COMMENT '资源ID（0表示该类型全部资源）',
    share_type TINYINT COMMENT '共享类型：1-按部门 2-按用户 3-按角色 4-公开',
    target_id BIGINT COMMENT '共享目标ID（部门ID/用户ID/角色ID）',
    target_name VARCHAR(128) COMMENT '共享目标名称',
    area_codes VARCHAR(512) COMMENT '允许的区域编码（逗号分隔，空表示全部区域）',
    pipeline_types VARCHAR(128) COMMENT '允许的管线类型（逗号分隔，空表示全部类型）',
    permission_type TINYINT COMMENT '权限类型：1-查看 2-编辑 3-审批 4-全部',
    effective_start_time VARCHAR(20) COMMENT '生效开始时间',
    effective_end_time VARCHAR(20) COMMENT '生效结束时间',
    status TINYINT DEFAULT 1 COMMENT '状态：1-启用 2-停用',
    creator VARCHAR(64) COMMENT '创建人',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    INDEX idx_target (share_type, target_id),
    INDEX idx_resource (resource_type, resource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='共享范围控制表';

DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    username VARCHAR(64) NOT NULL COMMENT '用户名',
    password VARCHAR(128) NOT NULL COMMENT '密码',
    real_name VARCHAR(64) COMMENT '真实姓名',
    phone VARCHAR(32) COMMENT '手机号',
    email VARCHAR(128) COMMENT '邮箱',
    avatar VARCHAR(512) COMMENT '头像URL',
    dept_id BIGINT COMMENT '部门ID',
    dept_name VARCHAR(128) COMMENT '部门名称',
    role_ids VARCHAR(256) COMMENT '角色ID列表（逗号分隔）',
    area_codes VARCHAR(512) COMMENT '负责区域编码（逗号分隔）',
    pipeline_types VARCHAR(128) COMMENT '负责管线类型（逗号分隔）',
    status TINYINT DEFAULT 1 COMMENT '状态：1-启用 2-停用',
    last_login_time VARCHAR(20) COMMENT '最后登录时间',
    last_login_ip VARCHAR(64) COMMENT '最后登录IP',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_username (username),
    INDEX idx_dept_id (dept_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

DROP TABLE IF EXISTS sys_department;
CREATE TABLE sys_department (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    dept_code VARCHAR(64) NOT NULL COMMENT '部门编号',
    dept_name VARCHAR(128) NOT NULL COMMENT '部门名称',
    parent_id BIGINT COMMENT '父级部门ID',
    dept_type TINYINT COMMENT '部门类型：1-管理部门 2-运维部门 3-审批部门 4-施工单位 5-产权单位',
    leader VARCHAR(64) COMMENT '负责人',
    phone VARCHAR(32) COMMENT '联系电话',
    area_codes VARCHAR(512) COMMENT '负责区域编码（逗号分隔）',
    pipeline_types VARCHAR(128) COMMENT '负责管线类型（逗号分隔）',
    sort INT DEFAULT 0 COMMENT '排序',
    status TINYINT DEFAULT 1 COMMENT '状态：1-启用 2-停用',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_dept_code (dept_code),
    INDEX idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部门表';

-- ========================================
-- 初始化数据
-- ========================================

INSERT INTO sys_department (dept_code, dept_name, parent_id, dept_type, leader, phone, area_codes, pipeline_types, sort, status) VALUES
('DEPT001', '城市管理局', 0, 1, '张局长', '13800000001', '110101,110102,110105', '1,2,3,4,5,6,7', 1, 1),
('DEPT002', '给排水管理中心', 1, 2, '李主任', '13800000002', '110101,110102', '1,2', 2, 1),
('DEPT003', '燃气管理中心', 1, 2, '王主任', '13800000003', '110101,110105', '3', 3, 1),
('DEPT004', '管线审批科', 1, 3, '赵科长', '13800000004', '110101,110102,110105', '1,2,3,4,5,6,7', 4, 1),
('DEPT005', '市政维修公司', 0, 4, '钱经理', '13800000005', '110101,110102,110105', '1,2,3,4,5,6,7', 5, 1);

INSERT INTO sys_user (username, password, real_name, phone, email, dept_id, dept_name, role_ids, area_codes, pipeline_types, status) VALUES
('admin', 'admin123', '系统管理员', '13800000000', 'admin@pipeline.com', 1, '城市管理局', '1', '110101,110102,110105', '1,2,3,4,5,6,7', 1),
('zhangsan', '123456', '张三', '13800000011', 'zhangsan@pipeline.com', 2, '给排水管理中心', '2', '110101,110102', '1,2', 1),
('lisi', '123456', '李四', '13800000012', 'lisi@pipeline.com', 3, '燃气管理中心', '2', '110101,110105', '3', 1),
('wangwu', '123456', '王五', '13800000013', 'wangwu@pipeline.com', 5, '市政维修公司', '3', '110101,110102,110105', '1,2,3,4,5,6,7', 1),
('zhaoliu', '123456', '赵六', '13800000014', 'zhaoliu@pipeline.com', 4, '管线审批科', '4', '110101,110102,110105', '1,2,3,4,5,6,7', 1);
